# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError as core_api_error_ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.api_error import ApiError as types_api_error_ApiError
from ..types.temporary_credential_response_envelope import TemporaryCredentialResponseEnvelope
from ..types.temporary_credential_subject import TemporaryCredentialSubject
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawTemporaryCredentialsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create(
        self,
        *,
        subject: TemporaryCredentialSubject,
        duration_seconds: typing.Optional[int] = OMIT,
        session_name: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TemporaryCredentialResponseEnvelope]:
        """
        Issues a non-renewable credential with a bounded lifetime for a user or Agent Data profile.

        The response contains the credential secret once. Store it securely and send it
        as a Bearer token in the `Authorization` header.

        Set `subject.type` to `user` to issue a credential for your authenticated user.
        Omit `organization_id` and `user_id`; Polytomic derives both values from your
        credential. Set `mode` to `read_only` to limit the credential to the
        intersection of the user's current permissions and read-only actions. A
        read-only caller can issue only read-only credentials.

        Partner callers must provide both `organization_id` and `user_id`. The target
        must be an active user in an organization owned by the partner. User subjects
        must be application users; Agent Data portal-only users continue to use profile
        credentials.

        User credentials resolve the subject's current permissions on every request.
        Permission changes take effect immediately, and deleting the user invalidates
        the credential.

        Set `subject.type` to `profile` and provide the Agent Data profile ID. The
        credential uses the profile's current connection access on every request;
        changes take effect immediately, and deleting the profile invalidates the
        credential.

        A temporary credential stops authenticating at `expires_at`. It cannot be
        refreshed, extended, or used to create another temporary credential. Create a
        new credential with a durable authorized credential when you need a later
        expiration.

        Each organization may have up to 1,000 active temporary credentials. The
        endpoint returns `429 Too Many Requests` at the limit. Expired credentials stop
        counting toward the limit immediately, before periodic cleanup removes them.

        > ⚠️ Session names are audit labels
        >
        > Use `session_name` only for non-sensitive job or agent-session correlation.
        > Do not include secrets or personal data.

        Polytomic periodically removes expired credential records. API usage history
        keeps its credential ID according to the normal API usage retention period.

        Parameters
        ----------
        subject : TemporaryCredentialSubject

        duration_seconds : typing.Optional[int]
            Credential lifetime in seconds. Defaults to 3600 (1 hour); minimum 600 and maximum 14400.

        session_name : typing.Optional[str]
            Optional audit correlation label, limited to 128 characters. Do not include secrets or personal data.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TemporaryCredentialResponseEnvelope]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/temporary-credentials",
            method="POST",
            json={
                "duration_seconds": duration_seconds,
                "session_name": session_name,
                "subject": convert_and_respect_annotation_metadata(
                    object_=subject, annotation=TemporaryCredentialSubject, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TemporaryCredentialResponseEnvelope,
                    parse_obj_as(
                        type_=TemporaryCredentialResponseEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise core_api_error_ApiError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
            )
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise core_api_error_ApiError(
            status_code=_response.status_code, headers=dict(_response.headers), body=_response_json
        )


class AsyncRawTemporaryCredentialsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create(
        self,
        *,
        subject: TemporaryCredentialSubject,
        duration_seconds: typing.Optional[int] = OMIT,
        session_name: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TemporaryCredentialResponseEnvelope]:
        """
        Issues a non-renewable credential with a bounded lifetime for a user or Agent Data profile.

        The response contains the credential secret once. Store it securely and send it
        as a Bearer token in the `Authorization` header.

        Set `subject.type` to `user` to issue a credential for your authenticated user.
        Omit `organization_id` and `user_id`; Polytomic derives both values from your
        credential. Set `mode` to `read_only` to limit the credential to the
        intersection of the user's current permissions and read-only actions. A
        read-only caller can issue only read-only credentials.

        Partner callers must provide both `organization_id` and `user_id`. The target
        must be an active user in an organization owned by the partner. User subjects
        must be application users; Agent Data portal-only users continue to use profile
        credentials.

        User credentials resolve the subject's current permissions on every request.
        Permission changes take effect immediately, and deleting the user invalidates
        the credential.

        Set `subject.type` to `profile` and provide the Agent Data profile ID. The
        credential uses the profile's current connection access on every request;
        changes take effect immediately, and deleting the profile invalidates the
        credential.

        A temporary credential stops authenticating at `expires_at`. It cannot be
        refreshed, extended, or used to create another temporary credential. Create a
        new credential with a durable authorized credential when you need a later
        expiration.

        Each organization may have up to 1,000 active temporary credentials. The
        endpoint returns `429 Too Many Requests` at the limit. Expired credentials stop
        counting toward the limit immediately, before periodic cleanup removes them.

        > ⚠️ Session names are audit labels
        >
        > Use `session_name` only for non-sensitive job or agent-session correlation.
        > Do not include secrets or personal data.

        Polytomic periodically removes expired credential records. API usage history
        keeps its credential ID according to the normal API usage retention period.

        Parameters
        ----------
        subject : TemporaryCredentialSubject

        duration_seconds : typing.Optional[int]
            Credential lifetime in seconds. Defaults to 3600 (1 hour); minimum 600 and maximum 14400.

        session_name : typing.Optional[str]
            Optional audit correlation label, limited to 128 characters. Do not include secrets or personal data.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TemporaryCredentialResponseEnvelope]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/temporary-credentials",
            method="POST",
            json={
                "duration_seconds": duration_seconds,
                "session_name": session_name,
                "subject": convert_and_respect_annotation_metadata(
                    object_=subject, annotation=TemporaryCredentialSubject, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TemporaryCredentialResponseEnvelope,
                    parse_obj_as(
                        type_=TemporaryCredentialResponseEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise core_api_error_ApiError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
            )
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise core_api_error_ApiError(
            status_code=_response.status_code, headers=dict(_response.headers), body=_response_json
        )
