# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.query_results_envelope import QueryResultsEnvelope
from ..types.run_query_envelope import RunQueryEnvelope
from .raw_client import AsyncRawQueryRunnerClient, RawQueryRunnerClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class QueryRunnerClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawQueryRunnerClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawQueryRunnerClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawQueryRunnerClient
        """
        return self._raw_client

    def run_query(
        self,
        connection_id: str,
        *,
        query: typing.Optional[str] = None,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RunQueryEnvelope:
        """
        Submits a query for asynchronous execution against the connection.

        This endpoint returns immediately with a query task ID. It does not wait for
        the query to finish. Poll [`GET /api/queries/{id}`](../../../../api-reference/query-runner/get-query) until `status`
        reaches `done` or `failed`.

        Only the user who created the query can fetch its results later. Query results
        are stored temporarily and may expire; use the `expires` field from the result
        endpoint to understand how long they will remain available.

        Parameters
        ----------
        connection_id : str
            Unique identifier of the connection to run the query against.

        query : typing.Optional[str]
            The query to execute against the connection.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RunQueryEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.query_runner.run_query(
            connection_id="248df4b7-aa70-47b8-a036-33ac447e668d",
            query="SELECT * FROM table",
        )
        """
        _response = self._raw_client.run_query(
            connection_id, query=query, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def get_query(
        self, id: str, *, page: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> QueryResultsEnvelope:
        """
        Fetches the latest status for a submitted query and, once complete, returns fields and paginated results.

        This endpoint is the second step of the query-runner flow. First call
        [`POST /api/connections/{connection_id}/query`](../../../api-reference/query-runner/run-query),
        then poll this endpoint with the returned ID.

        Results may be paginated across multiple blobs. When that happens, use the
        opaque `links.next` and `links.previous` URLs exactly as returned. Do not try to
        construct the `page` token yourself.

        If the query is still running, the response may include only status metadata.
        If the task is complete but the caller is not the same user that created it,
        the endpoint returns `404`.

        Parameters
        ----------
        id : str
            Unique identifier of the query task, as returned by POST /api/connections/{connection_id}/query.

        page : typing.Optional[str]
            Opaque pagination token returned in the links.next or links.previous URL of the previous response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QueryResultsEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.query_runner.get_query(
            id="248df4b7-aa70-47b8-a036-33ac447e668d",
            page="page",
        )
        """
        _response = self._raw_client.get_query(id, page=page, request_options=request_options)
        return _response.data


class AsyncQueryRunnerClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawQueryRunnerClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawQueryRunnerClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawQueryRunnerClient
        """
        return self._raw_client

    async def run_query(
        self,
        connection_id: str,
        *,
        query: typing.Optional[str] = None,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RunQueryEnvelope:
        """
        Submits a query for asynchronous execution against the connection.

        This endpoint returns immediately with a query task ID. It does not wait for
        the query to finish. Poll [`GET /api/queries/{id}`](../../../../api-reference/query-runner/get-query) until `status`
        reaches `done` or `failed`.

        Only the user who created the query can fetch its results later. Query results
        are stored temporarily and may expire; use the `expires` field from the result
        endpoint to understand how long they will remain available.

        Parameters
        ----------
        connection_id : str
            Unique identifier of the connection to run the query against.

        query : typing.Optional[str]
            The query to execute against the connection.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RunQueryEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.query_runner.run_query(
                connection_id="248df4b7-aa70-47b8-a036-33ac447e668d",
                query="SELECT * FROM table",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.run_query(
            connection_id, query=query, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def get_query(
        self, id: str, *, page: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> QueryResultsEnvelope:
        """
        Fetches the latest status for a submitted query and, once complete, returns fields and paginated results.

        This endpoint is the second step of the query-runner flow. First call
        [`POST /api/connections/{connection_id}/query`](../../../api-reference/query-runner/run-query),
        then poll this endpoint with the returned ID.

        Results may be paginated across multiple blobs. When that happens, use the
        opaque `links.next` and `links.previous` URLs exactly as returned. Do not try to
        construct the `page` token yourself.

        If the query is still running, the response may include only status metadata.
        If the task is complete but the caller is not the same user that created it,
        the endpoint returns `404`.

        Parameters
        ----------
        id : str
            Unique identifier of the query task, as returned by POST /api/connections/{connection_id}/query.

        page : typing.Optional[str]
            Opaque pagination token returned in the links.next or links.previous URL of the previous response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QueryResultsEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.query_runner.get_query(
                id="248df4b7-aa70-47b8-a036-33ac447e668d",
                page="page",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_query(id, page=page, request_options=request_options)
        return _response.data
