# This file was auto-generated by Fern from our API Definition.

from .types_type import TypesType
from .api_error import ApiError
from .backend_connection_capabilities import BackendConnectionCapabilities
from .backend_o_auth_prompt import BackendOAuthPrompt
from .bulk_bulk_sync_schedule import BulkBulkSyncSchedule
from .bulk_discover import BulkDiscover
from .bulk_execution_status import BulkExecutionStatus
from .bulk_itemized_schedule import BulkItemizedSchedule
from .bulk_multi_schedule_configuration import BulkMultiScheduleConfiguration
from .bulk_normalize_names import BulkNormalizeNames
from .bulk_schedule import BulkSchedule
from .bulk_schema_execution_status import BulkSchemaExecutionStatus
from .bulk_selective_mode import BulkSelectiveMode
from .bulk_sync_target_mode import BulkSyncTargetMode
from .common_output_actor import CommonOutputActor
from .eventing_bulk_sync_canceled_event import EventingBulkSyncCanceledEvent
from .eventing_bulk_sync_completed_event import EventingBulkSyncCompletedEvent
from .eventing_bulk_sync_completed_with_error_event import EventingBulkSyncCompletedWithErrorEvent
from .eventing_bulk_sync_failed_event import EventingBulkSyncFailedEvent
from .eventing_bulk_sync_running_event import EventingBulkSyncRunningEvent
from .eventing_sync_canceled_event import EventingSyncCanceledEvent
from .eventing_sync_completed_event import EventingSyncCompletedEvent
from .eventing_sync_completed_with_errors_event import EventingSyncCompletedWithErrorsEvent
from .eventing_sync_failed_event import EventingSyncFailedEvent
from .eventing_sync_running_event import EventingSyncRunningEvent
from .filter_field_reference_type import FilterFieldReferenceType
from .filter_function import FilterFunction
from .jsonschema_definitions import JsonschemaDefinitions
from .jsonschema_form import JsonschemaForm
from .jsonschema_schema import JsonschemaSchema
from .label_label import LabelLabel
from .model_model_field_request import ModelModelFieldRequest
from .model_relation import ModelRelation
from .model_relation_to import ModelRelationTo
from .modelsync_sync_target_mode import ModelsyncSyncTargetMode
from .rest_err_response import RestErrResponse
from .schedule_frequency import ScheduleFrequency
from .schedule_schedule_option import ScheduleScheduleOption
from .schema_association import SchemaAssociation
from .schema_identity_function import SchemaIdentityFunction
from .schema_primary_key_override_input import SchemaPrimaryKeyOverrideInput
from .sync_destination_properties import SyncDestinationProperties
from .target_create_input import TargetCreateInput
from .util_enum_value import UtilEnumValue
from .util_execution_status import UtilExecutionStatus
from .util_field_type import UtilFieldType
from .v_2_activate_sync_envelope import V2ActivateSyncEnvelope
from .v_2_activate_sync_input import V2ActivateSyncInput
from .v_2_activate_sync_output import V2ActivateSyncOutput
from .v_2_api_key_response import V2ApiKeyResponse
from .v_2_api_key_response_envelope import V2ApiKeyResponseEnvelope
from .v_2_bulk_filter import V2BulkFilter
from .v_2_bulk_sync_dest import V2BulkSyncDest
from .v_2_bulk_sync_dest_envelope import V2BulkSyncDestEnvelope
from .v_2_bulk_sync_list_envelope import V2BulkSyncListEnvelope
from .v_2_bulk_sync_response import V2BulkSyncResponse
from .v_2_bulk_sync_response_envelope import V2BulkSyncResponseEnvelope
from .v_2_cancel_sync_response import V2CancelSyncResponse
from .v_2_cancel_sync_response_envelope import V2CancelSyncResponseEnvelope
from .v_2_configuration_value import V2ConfigurationValue
from .v_2_connection_form import V2ConnectionForm
from .v_2_connection_list_response_envelope import V2ConnectionListResponseEnvelope
from .v_2_connection_meta import V2ConnectionMeta
from .v_2_connection_meta_response import V2ConnectionMetaResponse
from .v_2_connection_parameter_value import V2ConnectionParameterValue
from .v_2_connection_parameter_values_resp import V2ConnectionParameterValuesResp
from .v_2_connection_parameter_values_response_envelope import V2ConnectionParameterValuesResponseEnvelope
from .v_2_connection_response_envelope import V2ConnectionResponseEnvelope
from .v_2_connection_response_schema import V2ConnectionResponseSchema
from .v_2_connection_type import V2ConnectionType
from .v_2_connection_type_response_envelope import V2ConnectionTypeResponseEnvelope
from .v_2_connection_type_schema import V2ConnectionTypeSchema
from .v_2_create_connection_response_envelope import V2CreateConnectionResponseEnvelope
from .v_2_create_connection_response_schema import V2CreateConnectionResponseSchema
from .v_2_create_model_request import V2CreateModelRequest
from .v_2_enricher_configuration import V2EnricherConfiguration
from .v_2_enricher_mapping import V2EnricherMapping
from .v_2_enrichment import V2Enrichment
from .v_2_event import V2Event
from .v_2_event_payload import V2EventPayload
from .v_2_event_types_envelope import V2EventTypesEnvelope
from .v_2_events_envelope import V2EventsEnvelope
from .v_2_execution_counts import V2ExecutionCounts
from .v_2_execution_log_response import V2ExecutionLogResponse
from .v_2_execution_log_type import V2ExecutionLogType
from .v_2_execution_logs_response_envelope import V2ExecutionLogsResponseEnvelope
from .v_2_field_configuration import V2FieldConfiguration
from .v_2_filter import V2Filter
from .v_2_get_connection_meta_envelope import V2GetConnectionMetaEnvelope
from .v_2_get_enrichment_input_fields_response_envelope import V2GetEnrichmentInputFieldsResponseEnvelope
from .v_2_get_execution_response_envelope import V2GetExecutionResponseEnvelope
from .v_2_get_execution_response_schema import V2GetExecutionResponseSchema
from .v_2_get_identity_response_envelope import V2GetIdentityResponseEnvelope
from .v_2_get_identity_response_schema import V2GetIdentityResponseSchema
from .v_2_identity import V2Identity
from .v_2_identity_function import V2IdentityFunction
from .v_2_job_response import V2JobResponse
from .v_2_job_response_envelope import V2JobResponseEnvelope
from .v_2_list_execution_response_envelope import V2ListExecutionResponseEnvelope
from .v_2_list_policies_response_envelope import V2ListPoliciesResponseEnvelope
from .v_2_list_sync_response_envelope import V2ListSyncResponseEnvelope
from .v_2_list_users_envelope import V2ListUsersEnvelope
from .v_2_mode import V2Mode
from .v_2_model_field import V2ModelField
from .v_2_model_field_response import V2ModelFieldResponse
from .v_2_model_list_response_envelope import V2ModelListResponseEnvelope
from .v_2_model_response import V2ModelResponse
from .v_2_model_response_envelope import V2ModelResponseEnvelope
from .v_2_model_sample import V2ModelSample
from .v_2_model_sample_response_envelope import V2ModelSampleResponseEnvelope
from .v_2_ordered_map_string_github_com_invopop_jsonschema_schema import (
    V2OrderedMapStringGithubComInvopopJsonschemaSchema,
)
from .v_2_organization import V2Organization
from .v_2_organization_envelope import V2OrganizationEnvelope
from .v_2_organizations_envelope import V2OrganizationsEnvelope
from .v_2_override import V2Override
from .v_2_pagination_details import V2PaginationDetails
from .v_2_policy_action import V2PolicyAction
from .v_2_policy_response import V2PolicyResponse
from .v_2_policy_response_envelope import V2PolicyResponseEnvelope
from .v_2_relation import V2Relation
from .v_2_relation_to import V2RelationTo
from .v_2_role_list_response_envelope import V2RoleListResponseEnvelope
from .v_2_role_response import V2RoleResponse
from .v_2_role_response_envelope import V2RoleResponseEnvelope
from .v_2_run_after import V2RunAfter
from .v_2_sample_record import V2SampleRecord
from .v_2_schedule import V2Schedule
from .v_2_schedule_option_response import V2ScheduleOptionResponse
from .v_2_schedule_option_response_envelope import V2ScheduleOptionResponseEnvelope
from .v_2_schema_configuration import V2SchemaConfiguration
from .v_2_schema_configuration_fields_item import V2SchemaConfigurationFieldsItem
from .v_2_source import V2Source
from .v_2_start_sync_response_envelope import V2StartSyncResponseEnvelope
from .v_2_start_sync_response_schema import V2StartSyncResponseSchema
from .v_2_supported_bulk_mode import V2SupportedBulkMode
from .v_2_sync_field import V2SyncField
from .v_2_sync_response import V2SyncResponse
from .v_2_sync_response_envelope import V2SyncResponseEnvelope
from .v_2_sync_status_envelope import V2SyncStatusEnvelope
from .v_2_sync_status_response import V2SyncStatusResponse
from .v_2_target import V2Target
from .v_2_target_field import V2TargetField
from .v_2_target_response import V2TargetResponse
from .v_2_target_response_envelope import V2TargetResponseEnvelope
from .v_2_user import V2User
from .v_2_user_envelope import V2UserEnvelope
from .v_2_webhook import V2Webhook
from .v_2_webhook_envelope import V2WebhookEnvelope
from .v_2_webhook_list_envelope import V2WebhookListEnvelope
from .v_3_bulk_fetch_mode import V3BulkFetchMode
from .v_3_bulk_field import V3BulkField
from .v_3_bulk_filter import V3BulkFilter
from .v_3_bulk_schema import V3BulkSchema
from .v_3_bulk_schema_envelope import V3BulkSchemaEnvelope
from .v_3_bulk_sync_execution import V3BulkSyncExecution
from .v_3_bulk_sync_execution_envelope import V3BulkSyncExecutionEnvelope
from .v_3_bulk_sync_schema_execution import V3BulkSyncSchemaExecution
from .v_3_bulk_sync_source import V3BulkSyncSource
from .v_3_bulk_sync_source_envelope import V3BulkSyncSourceEnvelope
from .v_3_bulk_sync_source_schema_envelope import V3BulkSyncSourceSchemaEnvelope
from .v_3_bulk_sync_source_status import V3BulkSyncSourceStatus
from .v_3_bulk_sync_source_status_envelope import V3BulkSyncSourceStatusEnvelope
from .v_3_bulk_sync_status_envelope import V3BulkSyncStatusEnvelope
from .v_3_bulk_sync_status_response import V3BulkSyncStatusResponse
from .v_3_connect_card_response import V3ConnectCardResponse
from .v_3_connect_card_response_envelope import V3ConnectCardResponseEnvelope
from .v_3_list_bulk_schema_envelope import V3ListBulkSchemaEnvelope
from .v_3_list_bulk_sync_executions_envelope import V3ListBulkSyncExecutionsEnvelope
from .v_3_pagination_details import V3PaginationDetails
from .v_3_pick_value import V3PickValue
from .v_3_schema import V3Schema
from .v_3_schema_field import V3SchemaField
from .v_3_schema_records_response_envelope import V3SchemaRecordsResponseEnvelope
from .v_3_update_bulk_field import V3UpdateBulkField
from .v_4_bulk_sync_execution_logs import V4BulkSyncExecutionLogs
from .v_4_bulk_sync_execution_logs_envelope import V4BulkSyncExecutionLogsEnvelope
from .v_4_bulk_sync_execution_status import V4BulkSyncExecutionStatus
from .v_4_bulk_sync_schedule_api import V4BulkSyncScheduleApi
from .v_4_bulk_sync_schema_execution_status import V4BulkSyncSchemaExecutionStatus
from .v_4_configuration_value import V4ConfigurationValue
from .v_4_export_sync_logs_envelope import V4ExportSyncLogsEnvelope
from .v_4_export_sync_logs_response import V4ExportSyncLogsResponse
from .v_4_get_sync_source_meta_envelope import V4GetSyncSourceMetaEnvelope
from .v_4_global_error_subscribers_response import V4GlobalErrorSubscribersResponse
from .v_4_list_bulk_sync_executions_status_envelope import V4ListBulkSyncExecutionsStatusEnvelope
from .v_4_query_results_envelope import V4QueryResultsEnvelope
from .v_4_run_query_envelope import V4RunQueryEnvelope
from .v_4_run_query_pagination import V4RunQueryPagination
from .v_4_run_query_result import V4RunQueryResult
from .v_4_schedule_envelope import V4ScheduleEnvelope
from .v_4_schedules_envelope import V4SchedulesEnvelope
from .v_4_source_meta import V4SourceMeta
from .v_4_supported_mode import V4SupportedMode
from .v_4_sync_source_meta_response import V4SyncSourceMetaResponse
from .v_4_target_creator import V4TargetCreator
from .v_4_target_object import V4TargetObject
from .v_4_target_objects_response_envelope import V4TargetObjectsResponseEnvelope
from .v_4_target_property_values import V4TargetPropertyValues
from .v_4_target_property_values_envelope import V4TargetPropertyValuesEnvelope
from .v_4_user_field_request import V4UserFieldRequest
from .work_task_status import WorkTaskStatus

__all__ = [
    "ApiError",
    "BackendConnectionCapabilities",
    "BackendOAuthPrompt",
    "BulkBulkSyncSchedule",
    "BulkDiscover",
    "BulkExecutionStatus",
    "BulkItemizedSchedule",
    "BulkMultiScheduleConfiguration",
    "BulkNormalizeNames",
    "BulkSchedule",
    "BulkSchemaExecutionStatus",
    "BulkSelectiveMode",
    "BulkSyncTargetMode",
    "CommonOutputActor",
    "EventingBulkSyncCanceledEvent",
    "EventingBulkSyncCompletedEvent",
    "EventingBulkSyncCompletedWithErrorEvent",
    "EventingBulkSyncFailedEvent",
    "EventingBulkSyncRunningEvent",
    "EventingSyncCanceledEvent",
    "EventingSyncCompletedEvent",
    "EventingSyncCompletedWithErrorsEvent",
    "EventingSyncFailedEvent",
    "EventingSyncRunningEvent",
    "FilterFieldReferenceType",
    "FilterFunction",
    "JsonschemaDefinitions",
    "JsonschemaForm",
    "JsonschemaSchema",
    "LabelLabel",
    "ModelModelFieldRequest",
    "ModelRelation",
    "ModelRelationTo",
    "ModelsyncSyncTargetMode",
    "RestErrResponse",
    "ScheduleFrequency",
    "ScheduleScheduleOption",
    "SchemaAssociation",
    "SchemaIdentityFunction",
    "SchemaPrimaryKeyOverrideInput",
    "SyncDestinationProperties",
    "TargetCreateInput",
    "TypesType",
    "UtilEnumValue",
    "UtilExecutionStatus",
    "UtilFieldType",
    "V2ActivateSyncEnvelope",
    "V2ActivateSyncInput",
    "V2ActivateSyncOutput",
    "V2ApiKeyResponse",
    "V2ApiKeyResponseEnvelope",
    "V2BulkFilter",
    "V2BulkSyncDest",
    "V2BulkSyncDestEnvelope",
    "V2BulkSyncListEnvelope",
    "V2BulkSyncResponse",
    "V2BulkSyncResponseEnvelope",
    "V2CancelSyncResponse",
    "V2CancelSyncResponseEnvelope",
    "V2ConfigurationValue",
    "V2ConnectionForm",
    "V2ConnectionListResponseEnvelope",
    "V2ConnectionMeta",
    "V2ConnectionMetaResponse",
    "V2ConnectionParameterValue",
    "V2ConnectionParameterValuesResp",
    "V2ConnectionParameterValuesResponseEnvelope",
    "V2ConnectionResponseEnvelope",
    "V2ConnectionResponseSchema",
    "V2ConnectionType",
    "V2ConnectionTypeResponseEnvelope",
    "V2ConnectionTypeSchema",
    "V2CreateConnectionResponseEnvelope",
    "V2CreateConnectionResponseSchema",
    "V2CreateModelRequest",
    "V2EnricherConfiguration",
    "V2EnricherMapping",
    "V2Enrichment",
    "V2Event",
    "V2EventPayload",
    "V2EventTypesEnvelope",
    "V2EventsEnvelope",
    "V2ExecutionCounts",
    "V2ExecutionLogResponse",
    "V2ExecutionLogType",
    "V2ExecutionLogsResponseEnvelope",
    "V2FieldConfiguration",
    "V2Filter",
    "V2GetConnectionMetaEnvelope",
    "V2GetEnrichmentInputFieldsResponseEnvelope",
    "V2GetExecutionResponseEnvelope",
    "V2GetExecutionResponseSchema",
    "V2GetIdentityResponseEnvelope",
    "V2GetIdentityResponseSchema",
    "V2Identity",
    "V2IdentityFunction",
    "V2JobResponse",
    "V2JobResponseEnvelope",
    "V2ListExecutionResponseEnvelope",
    "V2ListPoliciesResponseEnvelope",
    "V2ListSyncResponseEnvelope",
    "V2ListUsersEnvelope",
    "V2Mode",
    "V2ModelField",
    "V2ModelFieldResponse",
    "V2ModelListResponseEnvelope",
    "V2ModelResponse",
    "V2ModelResponseEnvelope",
    "V2ModelSample",
    "V2ModelSampleResponseEnvelope",
    "V2OrderedMapStringGithubComInvopopJsonschemaSchema",
    "V2Organization",
    "V2OrganizationEnvelope",
    "V2OrganizationsEnvelope",
    "V2Override",
    "V2PaginationDetails",
    "V2PolicyAction",
    "V2PolicyResponse",
    "V2PolicyResponseEnvelope",
    "V2Relation",
    "V2RelationTo",
    "V2RoleListResponseEnvelope",
    "V2RoleResponse",
    "V2RoleResponseEnvelope",
    "V2RunAfter",
    "V2SampleRecord",
    "V2Schedule",
    "V2ScheduleOptionResponse",
    "V2ScheduleOptionResponseEnvelope",
    "V2SchemaConfiguration",
    "V2SchemaConfigurationFieldsItem",
    "V2Source",
    "V2StartSyncResponseEnvelope",
    "V2StartSyncResponseSchema",
    "V2SupportedBulkMode",
    "V2SyncField",
    "V2SyncResponse",
    "V2SyncResponseEnvelope",
    "V2SyncStatusEnvelope",
    "V2SyncStatusResponse",
    "V2Target",
    "V2TargetField",
    "V2TargetResponse",
    "V2TargetResponseEnvelope",
    "V2User",
    "V2UserEnvelope",
    "V2Webhook",
    "V2WebhookEnvelope",
    "V2WebhookListEnvelope",
    "V3BulkFetchMode",
    "V3BulkField",
    "V3BulkFilter",
    "V3BulkSchema",
    "V3BulkSchemaEnvelope",
    "V3BulkSyncExecution",
    "V3BulkSyncExecutionEnvelope",
    "V3BulkSyncSchemaExecution",
    "V3BulkSyncSource",
    "V3BulkSyncSourceEnvelope",
    "V3BulkSyncSourceSchemaEnvelope",
    "V3BulkSyncSourceStatus",
    "V3BulkSyncSourceStatusEnvelope",
    "V3BulkSyncStatusEnvelope",
    "V3BulkSyncStatusResponse",
    "V3ConnectCardResponse",
    "V3ConnectCardResponseEnvelope",
    "V3ListBulkSchemaEnvelope",
    "V3ListBulkSyncExecutionsEnvelope",
    "V3PaginationDetails",
    "V3PickValue",
    "V3Schema",
    "V3SchemaField",
    "V3SchemaRecordsResponseEnvelope",
    "V3UpdateBulkField",
    "V4BulkSyncExecutionLogs",
    "V4BulkSyncExecutionLogsEnvelope",
    "V4BulkSyncExecutionStatus",
    "V4BulkSyncScheduleApi",
    "V4BulkSyncSchemaExecutionStatus",
    "V4ConfigurationValue",
    "V4ExportSyncLogsEnvelope",
    "V4ExportSyncLogsResponse",
    "V4GetSyncSourceMetaEnvelope",
    "V4GlobalErrorSubscribersResponse",
    "V4ListBulkSyncExecutionsStatusEnvelope",
    "V4QueryResultsEnvelope",
    "V4RunQueryEnvelope",
    "V4RunQueryPagination",
    "V4RunQueryResult",
    "V4ScheduleEnvelope",
    "V4SchedulesEnvelope",
    "V4SourceMeta",
    "V4SupportedMode",
    "V4SyncSourceMetaResponse",
    "V4TargetCreator",
    "V4TargetObject",
    "V4TargetObjectsResponseEnvelope",
    "V4TargetPropertyValues",
    "V4TargetPropertyValuesEnvelope",
    "V4UserFieldRequest",
    "WorkTaskStatus",
]
