# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .bulk_itemized_schedule import BulkItemizedSchedule
from .bulk_multi_schedule_configuration import BulkMultiScheduleConfiguration
from .bulk_schedule import BulkSchedule
import typing
from .bulk_sync_response import BulkSyncResponse
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class BulkSyncListEnvelope(UniversalBaseModel):
    data: typing.Optional[typing.List[BulkSyncResponse]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
