# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .bulk_discover import BulkDiscover
from .bulk_normalize_names import BulkNormalizeNames
from .bulk_sync_mode import BulkSyncMode
from .common_output_actor import CommonOutputActor


class BulkSyncResponse(UniversalBaseModel):
    active: typing.Optional[bool] = None
    automatically_add_new_fields: typing.Optional[BulkDiscover] = None
    automatically_add_new_objects: typing.Optional[BulkDiscover] = None
    concurrency_limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Per-sync concurrency limit override.
    """

    created_at: typing.Optional[dt.datetime] = None
    created_by: typing.Optional[CommonOutputActor] = None
    data_cutoff_timestamp: typing.Optional[dt.datetime] = None
    destination_configuration: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Destination-specific bulk sync configuration. e.g. output schema name, s3 file format, etc.
    """

    destination_connection_id: typing.Optional[str] = None
    disable_record_timestamps: typing.Optional[bool] = None
    discover: typing.Optional[bool] = pydantic.Field(default=None)
    """
    DEPRECATED: Use automatically_add_new_objects/automatically_add_new_fields instead
    """

    id: typing.Optional[str] = None
    mode: typing.Optional[BulkSyncMode] = None
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the bulk sync
    """

    normalize_names: typing.Optional[BulkNormalizeNames] = None
    organization_id: typing.Optional[str] = None
    policies: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of permissions policies applied to the bulk sync.
    """

    resync_concurrency_limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Per-sync resync concurrency limit override.
    """

    schedule: typing.Optional["BulkSchedule"] = None
    source_configuration: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Source-specific bulk sync configuration. e.g. replication slot name, sync lookback, etc.
    """

    source_connection_id: typing.Optional[str] = None
    updated_at: typing.Optional[dt.datetime] = None
    updated_by: typing.Optional[CommonOutputActor] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .bulk_itemized_schedule import BulkItemizedSchedule  # noqa: E402, I001
from .bulk_multi_schedule_configuration import BulkMultiScheduleConfiguration  # noqa: E402, I001
from .bulk_schedule import BulkSchedule  # noqa: E402, I001

update_forward_refs(
    BulkSyncResponse,
    BulkItemizedSchedule=BulkItemizedSchedule,
    BulkMultiScheduleConfiguration=BulkMultiScheduleConfiguration,
    BulkSchedule=BulkSchedule,
)
