# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
import datetime as dt
from ..core.serialization import FieldMetadata
from .schedule_frequency import ScheduleFrequency
from .bulk_selective_mode import BulkSelectiveMode
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class BulkBulkSyncSchedule(UniversalBaseModel):
    created_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="createdAt")] = None
    created_by: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="createdBy")] = None
    day_of_month: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="dayOfMonth")] = None
    day_of_week: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="dayOfWeek")] = None
    deleted_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="deletedAt")] = None
    deleted_by: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="deletedBy")] = None
    frequency: ScheduleFrequency
    hour: typing.Optional[str] = None
    minute: typing.Optional[str] = None
    month: typing.Optional[str] = None
    selective_mode: typing_extensions.Annotated[
        typing.Optional[BulkSelectiveMode], FieldMetadata(alias="selectiveMode")
    ] = None
    sync_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="syncId")] = None
    updated_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="updatedAt")] = None
    updated_by: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="updatedBy")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
