# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ConnectSessionResponse(UniversalBaseModel):
    connection_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Existing or newly-created connection bound to this session.
    """

    dark: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the Connect modal uses the dark theme.
    """

    expires_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Absolute time when the Connect session expires.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stable identifier for this Connect session.
    """

    logo: typing.Optional[str] = pydantic.Field(default=None)
    """
    Trusted logo URL displayed by the Connect modal.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Trusted connection name for this session.
    """

    organization_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Trusted organization or partner name displayed by the Connect modal.
    """

    redirect_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL to redirect to after the Connect flow finishes.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Fixed connection type for this session, if any.
    """

    whitelist: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Connection types allowed for this session when type is empty.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
