# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreateRecordViewLinkResponse(UniversalBaseModel):
    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Link creation timestamp.
    """

    expires_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Link expiry timestamp.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Record-view link identifier.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    One-time returned viewer URL containing the raw bearer token.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
