# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class HarborResponse(UniversalBaseModel):
    backing_connection_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Connection that provides the Harbor's queryable data store.
    """

    backing_mode: typing.Optional[str] = pydantic.Field(default=None)
    """
    How the Harbor's queryable data store is provided.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the Harbor was created.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Short description of the Harbor.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier of the Harbor.
    """

    mcp_server_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    MCP server URL for the Harbor.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable Harbor name.
    """

    organization_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Organization that owns the Harbor.
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the Harbor was last updated.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
