# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .harbor_saved_query_parameter import HarborSavedQueryParameter


class HarborSavedQueryResponse(UniversalBaseModel):
    change_note: typing.Optional[str] = pydantic.Field(default=None)
    """
    Note supplied when this version was published.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Business definition and usage notes.
    """

    expected_columns: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Expected ordered result-column names.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stable saved-query identifier.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable saved-query name.
    """

    owner: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable owner label.
    """

    parameters: typing.Optional[typing.List[HarborSavedQueryParameter]] = pydantic.Field(default=None)
    """
    Published typed scalar parameter declarations.
    """

    published_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When this version was published.
    """

    published_by: typing.Optional[str] = pydantic.Field(default=None)
    """
    Actor that published this version. Null for the system actor.
    """

    published_by_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Type of actor that published this version.
    """

    revision_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Immutable identifier of this exact published definition.
    """

    sql_template: typing.Optional[str] = pydantic.Field(default=None)
    """
    Published SQL template.
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When this version's draft was last updated before publication.
    """

    version: typing.Optional[int] = pydantic.Field(default=None)
    """
    Current published version number.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
