# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .work_task_status import WorkTaskStatus
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class JobResponse(UniversalBaseModel):
    error: typing.Optional[str] = None
    job_id: typing.Optional[str] = None
    result: typing.Optional[typing.Optional[typing.Any]] = None
    status: typing.Optional[WorkTaskStatus] = None
    type: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
