# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ModelField(UniversalBaseModel):
    description: typing.Optional[str] = None
    example: typing.Optional[typing.Optional[typing.Any]] = None
    id: typing.Optional[str] = None
    label: typing.Optional[str] = None
    name: typing.Optional[str] = None
    remote_type: typing.Optional[str] = None
    type: typing.Optional[str] = None
    unique: typing.Optional[bool] = None
    user_added: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
