# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .operation_search_rate_limit import OperationSearchRateLimit


class OperationSearchAvailabilityEnvelopeData(UniversalBaseModel):
    enabled: bool = pydantic.Field()
    """
    Whether operation search is configured on this API deployment.
    """

    rate_limited: typing.Optional[OperationSearchRateLimit] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
