# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .operation_search_rate_limit_reason import OperationSearchRateLimitReason


class OperationSearchRateLimit(UniversalBaseModel):
    reason: OperationSearchRateLimitReason = pydantic.Field()
    """
    The exhausted question budget.
    """

    reset_at: dt.datetime = pydantic.Field()
    """
    UTC time when this exhausted budget resets.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
