# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .source import Source
import pydantic
from .filter_function import FilterFunction
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class Override(UniversalBaseModel):
    """
    Either `field` or `field_id` must be provided. If `field_id` is provided, `field` is ignored.
    """

    field: typing.Optional[Source] = None
    field_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Field ID of the model field to override.
    """

    function: typing.Optional[FilterFunction] = None
    override: typing.Optional[typing.Optional[typing.Any]] = None
    value: typing.Optional[typing.Optional[typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
