# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .pick_value import PickValue
from .schema_association import SchemaAssociation
from .types_type import TypesType
from .util_field_type import UtilFieldType


class SchemaField(UniversalBaseModel):
    association: typing.Optional[SchemaAssociation] = None
    id: typing.Optional[str] = None
    is_primary_key: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this field is part of the schema's primary key, including any user override.
    """

    name: typing.Optional[str] = None
    path: typing.Optional[str] = pydantic.Field(default=None)
    """
    JSONPath used to extract the field from each source record; only meaningful for document-style backends.
    """

    primary_key_override: typing.Optional[bool] = pydantic.Field(default=None)
    """
    The user-set primary key status for this field, which takes precedence over source_primary_key; omitted when no override is set.
    """

    remote_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of the field from the remote system.
    """

    source_primary_key: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the source system reports this field as part of the schema's primary key.
    """

    type: typing.Optional[UtilFieldType] = None
    type_spec: typing.Optional[TypesType] = None
    user_managed: typing.Optional[bool] = pydantic.Field(default=None)
    """
    True when the field's effective definition came from a user override.
    """

    values: typing.Optional[typing.List[PickValue]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
