# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .v2create_connection_response_schema import V2CreateConnectionResponseSchema
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class V2CreateConnectionResponseEnvelope(UniversalBaseModel):
    data: typing.Optional[V2CreateConnectionResponseSchema] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
