# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .v3bulk_sync_execution import V3BulkSyncExecution
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class V3BulkSyncStatusResponse(UniversalBaseModel):
    current_execution: typing.Optional[V3BulkSyncExecution] = None
    last_execution: typing.Optional[V3BulkSyncExecution] = None
    next_execution_time: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
