# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .v5list_sync_item import V5ListSyncItem
from .v5pagination_details import V5PaginationDetails
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class V5ListSyncResponseEnvelope(UniversalBaseModel):
    data: typing.Optional[typing.List[V5ListSyncItem]] = None
    pagination: typing.Optional[V5PaginationDetails] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
