# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from ..core.serialization import FieldMetadata
from .v_2_relation_to import V2RelationTo
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class V2Relation(UniversalBaseModel):
    from_: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="from")] = None
    to: typing.Optional[V2RelationTo] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
