# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.role_list_response_envelope import RoleListResponseEnvelope
from ...types.role_response_envelope import RoleResponseEnvelope
from .raw_client import AsyncRawRolesClient, RawRolesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RolesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRolesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRolesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRolesClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> RoleListResponseEnvelope:
        """
        Lists all permissions roles available in the caller's organization, including built-in system roles.

        System roles such as Admin and Member are always present in every organization
        and cannot be modified or deleted. Custom roles appear alongside them and can
        be created, updated, or removed as needed.

        To inspect or modify a specific role, use
        [`GET /api/permissions/roles/{id}`](../../../api-reference/permissions/roles/get).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoleListResponseEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.permissions.roles.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        name: str,
        organization_id: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RoleResponseEnvelope:
        """
        Creates a new permissions role.

        Provide a `name` for the new role. The role is immediately available for use
        in permission policies.

        To attach the role to resources, create or update a policy using
        [`POST /api/permissions/policies`](../../../api-reference/permissions/policies/create).

        Parameters
        ----------
        name : str

        organization_id : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoleResponseEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.permissions.roles.create(
            name="Custom",
        )
        """
        _response = self._raw_client.create(
            name=name, organization_id=organization_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> RoleResponseEnvelope:
        """
        Returns a single permissions role by ID.

        Returns the role's name, action set, and whether it is a built-in system role.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoleResponseEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.permissions.roles.get(
            id="248df4b7-aa70-47b8-a036-33ac447e668d",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        name: str,
        organization_id: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RoleResponseEnvelope:
        """
        Updates an existing permissions role's name and action set.

        The update is a **full replacement** of the role definition.

        > 🚧 Built-in system roles (such as Admin and Member) cannot be updated.
        > Attempting to modify a system role returns an error.

        Parameters
        ----------
        id : str

        name : str

        organization_id : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoleResponseEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.permissions.roles.update(
            id="248df4b7-aa70-47b8-a036-33ac447e668d",
            name="Custom",
        )
        """
        _response = self._raw_client.update(
            id,
            name=name,
            organization_id=organization_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def remove(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Deletes a permissions role.

        > 🚧 Built-in system roles (such as Admin and Member) cannot be deleted.
        > Attempting to delete a system role returns an error.

        Deleting a role does not automatically remove it from any policies that
        reference it. Update those policies separately using
        [`PUT /api/permissions/policies/{id}`](../../../../api-reference/permissions/policies/update) to avoid
        leaving stale role references.

        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.permissions.roles.remove(
            id="248df4b7-aa70-47b8-a036-33ac447e668d",
        )
        """
        _response = self._raw_client.remove(id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data


class AsyncRolesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRolesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRolesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRolesClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> RoleListResponseEnvelope:
        """
        Lists all permissions roles available in the caller's organization, including built-in system roles.

        System roles such as Admin and Member are always present in every organization
        and cannot be modified or deleted. Custom roles appear alongside them and can
        be created, updated, or removed as needed.

        To inspect or modify a specific role, use
        [`GET /api/permissions/roles/{id}`](../../../api-reference/permissions/roles/get).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoleListResponseEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.permissions.roles.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        name: str,
        organization_id: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RoleResponseEnvelope:
        """
        Creates a new permissions role.

        Provide a `name` for the new role. The role is immediately available for use
        in permission policies.

        To attach the role to resources, create or update a policy using
        [`POST /api/permissions/policies`](../../../api-reference/permissions/policies/create).

        Parameters
        ----------
        name : str

        organization_id : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoleResponseEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.permissions.roles.create(
                name="Custom",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            name=name, organization_id=organization_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> RoleResponseEnvelope:
        """
        Returns a single permissions role by ID.

        Returns the role's name, action set, and whether it is a built-in system role.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoleResponseEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.permissions.roles.get(
                id="248df4b7-aa70-47b8-a036-33ac447e668d",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        name: str,
        organization_id: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RoleResponseEnvelope:
        """
        Updates an existing permissions role's name and action set.

        The update is a **full replacement** of the role definition.

        > 🚧 Built-in system roles (such as Admin and Member) cannot be updated.
        > Attempting to modify a system role returns an error.

        Parameters
        ----------
        id : str

        name : str

        organization_id : typing.Optional[str]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoleResponseEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.permissions.roles.update(
                id="248df4b7-aa70-47b8-a036-33ac447e668d",
                name="Custom",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            name=name,
            organization_id=organization_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def remove(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Deletes a permissions role.

        > 🚧 Built-in system roles (such as Admin and Member) cannot be deleted.
        > Attempting to delete a system role returns an error.

        Deleting a role does not automatically remove it from any policies that
        reference it. Update those policies separately using
        [`PUT /api/permissions/policies/{id}`](../../../../api-reference/permissions/policies/update) to avoid
        leaving stale role references.

        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.permissions.roles.remove(
                id="248df4b7-aa70-47b8-a036-33ac447e668d",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove(id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data
