# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.list_policies_response_envelope import ListPoliciesResponseEnvelope
from ...types.policy_action import PolicyAction
from ...types.policy_response_envelope import PolicyResponseEnvelope
from .raw_client import AsyncRawPoliciesClient, RawPoliciesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PoliciesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPoliciesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPoliciesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPoliciesClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListPoliciesResponseEnvelope:
        """
        Lists all policies in the caller's organization.

        Each policy binds one or more roles to a set of resources, controlling what
        actions members with those roles can perform on those resources.

        To inspect a specific policy in detail, use
        [`GET /api/permissions/policies/{id}`](../../../api-reference/permissions/policies/get).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPoliciesResponseEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.permissions.policies.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        name: str,
        organization_id: typing.Optional[str] = OMIT,
        policy_actions: typing.Optional[typing.Sequence[PolicyAction]] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PolicyResponseEnvelope:
        """
        Creates a new policy.

        A policy binds one or more roles to a set of resources, granting members who
        hold those roles the actions defined by them. Roles must already exist before
        they are referenced in a policy; create roles using
        [`POST /api/permissions/roles`](../../../api-reference/permissions/roles/create).

        Parameters
        ----------
        name : str

        organization_id : typing.Optional[str]

        policy_actions : typing.Optional[typing.Sequence[PolicyAction]]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PolicyResponseEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.permissions.policies.create(
            name="Custom",
        )
        """
        _response = self._raw_client.create(
            name=name,
            organization_id=organization_id,
            policy_actions=policy_actions,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> PolicyResponseEnvelope:
        """
        Returns a single policy by ID, including all action/role bindings it defines.

        Returns the full set of action/role bindings defined by the policy, including
        the resources it applies to.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PolicyResponseEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.permissions.policies.get(
            id="248df4b7-aa70-47b8-a036-33ac447e668d",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        name: str,
        organization_id: typing.Optional[str] = OMIT,
        policy_actions: typing.Optional[typing.Sequence[PolicyAction]] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PolicyResponseEnvelope:
        """
        Updates an existing policy.

        The update is a **full replacement** of the policy's bindings. Any role or
        resource binding not included in the request body is removed. To make a
        partial change, fetch the current policy with
        [`GET /api/permissions/policies/{id}`](../../../../api-reference/permissions/policies/get), modify the relevant bindings,
        and send the complete object back.

        Parameters
        ----------
        id : str

        name : str

        organization_id : typing.Optional[str]

        policy_actions : typing.Optional[typing.Sequence[PolicyAction]]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PolicyResponseEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.permissions.policies.update(
            id="248df4b7-aa70-47b8-a036-33ac447e668d",
            name="Custom",
        )
        """
        _response = self._raw_client.update(
            id,
            name=name,
            organization_id=organization_id,
            policy_actions=policy_actions,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def delete(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Deletes a policy.

        Deletion is permanent. Any access that was granted solely through this policy
        is revoked immediately for all users who depended on it.

        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.permissions.policies.delete(
            id="248df4b7-aa70-47b8-a036-33ac447e668d",
        )
        """
        _response = self._raw_client.delete(id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data


class AsyncPoliciesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPoliciesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPoliciesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPoliciesClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListPoliciesResponseEnvelope:
        """
        Lists all policies in the caller's organization.

        Each policy binds one or more roles to a set of resources, controlling what
        actions members with those roles can perform on those resources.

        To inspect a specific policy in detail, use
        [`GET /api/permissions/policies/{id}`](../../../api-reference/permissions/policies/get).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPoliciesResponseEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.permissions.policies.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        name: str,
        organization_id: typing.Optional[str] = OMIT,
        policy_actions: typing.Optional[typing.Sequence[PolicyAction]] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PolicyResponseEnvelope:
        """
        Creates a new policy.

        A policy binds one or more roles to a set of resources, granting members who
        hold those roles the actions defined by them. Roles must already exist before
        they are referenced in a policy; create roles using
        [`POST /api/permissions/roles`](../../../api-reference/permissions/roles/create).

        Parameters
        ----------
        name : str

        organization_id : typing.Optional[str]

        policy_actions : typing.Optional[typing.Sequence[PolicyAction]]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PolicyResponseEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.permissions.policies.create(
                name="Custom",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            name=name,
            organization_id=organization_id,
            policy_actions=policy_actions,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> PolicyResponseEnvelope:
        """
        Returns a single policy by ID, including all action/role bindings it defines.

        Returns the full set of action/role bindings defined by the policy, including
        the resources it applies to.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PolicyResponseEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.permissions.policies.get(
                id="248df4b7-aa70-47b8-a036-33ac447e668d",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        name: str,
        organization_id: typing.Optional[str] = OMIT,
        policy_actions: typing.Optional[typing.Sequence[PolicyAction]] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PolicyResponseEnvelope:
        """
        Updates an existing policy.

        The update is a **full replacement** of the policy's bindings. Any role or
        resource binding not included in the request body is removed. To make a
        partial change, fetch the current policy with
        [`GET /api/permissions/policies/{id}`](../../../../api-reference/permissions/policies/get), modify the relevant bindings,
        and send the complete object back.

        Parameters
        ----------
        id : str

        name : str

        organization_id : typing.Optional[str]

        policy_actions : typing.Optional[typing.Sequence[PolicyAction]]

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PolicyResponseEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.permissions.policies.update(
                id="248df4b7-aa70-47b8-a036-33ac447e668d",
                name="Custom",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            name=name,
            organization_id=organization_id,
            policy_actions=policy_actions,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def delete(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Deletes a policy.

        Deletion is permanent. Any access that was granted solely through this policy
        is revoked immediately for all users who depended on it.

        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.permissions.policies.delete(
                id="248df4b7-aa70-47b8-a036-33ac447e668d",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data
