# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.organization_envelope import OrganizationEnvelope
from ..types.organizations_envelope import OrganizationsEnvelope
from ..types.record_logging_settings_envelope import RecordLoggingSettingsEnvelope
from .raw_client import AsyncRawOrganizationClient, RawOrganizationClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OrganizationClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOrganizationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOrganizationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOrganizationClient
        """
        return self._raw_client

    def get_current(self, *, request_options: typing.Optional[RequestOptions] = None) -> OrganizationEnvelope:
        """
        Returns the organization the caller is authenticated against.

        This endpoint is the safest way to discover the effective organization for a
        user-scoped or organization-scoped credential. It does not let callers inspect
        arbitrary organizations; it only returns the organization implied by the
        credential that authenticated the request.

        If you need to enumerate or look up organizations across a partner account, use
        [`GET /api/organizations`](../../api-reference/organization/list) or
        [`GET /api/organizations/{id}`](../../api-reference/organization/get) instead.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.organization.get_current()
        """
        _response = self._raw_client.get_current(request_options=request_options)
        return _response.data

    def get_record_logging(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RecordLoggingSettingsEnvelope:
        """
        Returns the organization's record logging settings, including the connection record logs are delivered to.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecordLoggingSettingsEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.organization.get_record_logging()
        """
        _response = self._raw_client.get_record_logging(request_options=request_options)
        return _response.data

    def update_record_logging(
        self,
        *,
        enabled: bool,
        delivery_connection_id: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RecordLoggingSettingsEnvelope:
        """
        Replaces the organization's record logging settings. `deliveryConnectionId` is replaced, not merged: omitting it, or sending null, removes any destination previously configured.

        Parameters
        ----------
        enabled : bool
            Whether record logging is enabled for the organization.

        delivery_connection_id : typing.Optional[str]
            Blobstorage connection that receives record logs after each model sync execution. Omit or send null to deliver nowhere; this field is replaced, not merged.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecordLoggingSettingsEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.organization.update_record_logging(
            enabled=True,
        )
        """
        _response = self._raw_client.update_record_logging(
            enabled=enabled,
            delivery_connection_id=delivery_connection_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> OrganizationsEnvelope:
        """
        Lists every organization accessible to the calling partner, with the partner's owner organization first.

        In `2025-09-18`, this endpoint is partner-scoped rather than a general
        "current caller visibility" listing. The partner owner organization is returned
        first, followed by child organizations.

        This ordering matters for partner workflows such as shared connections, where
        the parent connection must live in the partner owner organization.

        If you need only the organization implied by the current credential, use
        [`GET /api/organization`](../../api-reference/organization/get-current) instead.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationsEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.organization.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        name: str,
        client_id: typing.Optional[str] = OMIT,
        client_secret: typing.Optional[str] = OMIT,
        issuer: typing.Optional[str] = OMIT,
        sso_domain: typing.Optional[str] = OMIT,
        sso_org_id: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrganizationEnvelope:
        """
        Creates a new organization under the calling partner account, optionally configuring SSO or OIDC at creation time.

        > 🚧 Requires partner key
        >
        > This endpoint is only accessible using [partner keys](../../guides/obtaining-api-keys#partner-keys).

        SSO and OIDC settings supplied at creation time can be updated later via
        `PUT /api/organizations/{id}`.

        Parameters
        ----------
        name : str
            Human-readable name of the organization. Must be unique across the partner account.

        client_id : typing.Optional[str]
            OIDC client ID issued by the identity provider.

        client_secret : typing.Optional[str]
            OIDC client secret issued by the identity provider. Write-only; never returned in responses.

        issuer : typing.Optional[str]
            OIDC issuer URL for organizations using OpenID Connect single sign-on.

        sso_domain : typing.Optional[str]
            Email domain used to match users to this organization during SSO sign-in.

        sso_org_id : typing.Optional[str]
            WorkOS organization identifier linking this organization to its SAML/SSO configuration.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.organization.create(
            name="My Organization",
        )
        """
        _response = self._raw_client.create(
            name=name,
            client_id=client_id,
            client_secret=client_secret,
            issuer=issuer,
            sso_domain=sso_domain,
            sso_org_id=sso_org_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> OrganizationEnvelope:
        """
        Returns a single organization by ID.

        > 📘 Credential scope varies by endpoint and API version
        >
        > Organization endpoints do not all share the same credential requirements.
        > Check each endpoint's description for the caller scope that applies in that
        > API version.

        Parameters
        ----------
        id : str
            Unique identifier of the organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.organization.get(
            id="248df4b7-aa70-47b8-a036-33ac447e668d",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        name: str,
        client_id: typing.Optional[str] = OMIT,
        client_secret: typing.Optional[str] = OMIT,
        issuer: typing.Optional[str] = OMIT,
        sso_domain: typing.Optional[str] = OMIT,
        sso_org_id: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrganizationEnvelope:
        """
        Updates an organization's name and SSO or OIDC configuration.

        > 🚧 Requires partner key
        >
        > This endpoint is only accessible using [partner keys](../../../guides/obtaining-api-keys#partner-keys).

        > 📘 SSO and OIDC configuration is replaced in full on each update. Include all
        > desired settings in the request body, not just the fields you want to change.

        Parameters
        ----------
        id : str
            Unique identifier of the organization to update.

        name : str
            Human-readable name of the organization. Must be unique across the partner account.

        client_id : typing.Optional[str]
            OIDC client ID issued by the identity provider.

        client_secret : typing.Optional[str]
            OIDC client secret issued by the identity provider. Write-only; never returned in responses.

        issuer : typing.Optional[str]
            OIDC issuer URL for organizations using OpenID Connect single sign-on.

        sso_domain : typing.Optional[str]
            Email domain used to match users to this organization during SSO sign-in.

        sso_org_id : typing.Optional[str]
            WorkOS organization identifier linking this organization to its SAML/SSO configuration.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationEnvelope
            OK

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.organization.update(
            id="248df4b7-aa70-47b8-a036-33ac447e668d",
            name="My Organization",
        )
        """
        _response = self._raw_client.update(
            id,
            name=name,
            client_id=client_id,
            client_secret=client_secret,
            issuer=issuer,
            sso_domain=sso_domain,
            sso_org_id=sso_org_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def delete(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Deletes an organization.

        Partner callers cannot delete their own owner organization.

        Parameters
        ----------
        id : str
            Unique identifier of the organization.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from polytomic import Polytomic

        client = Polytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )
        client.organization.delete(
            id="248df4b7-aa70-47b8-a036-33ac447e668d",
        )
        """
        _response = self._raw_client.delete(id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data


class AsyncOrganizationClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOrganizationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOrganizationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOrganizationClient
        """
        return self._raw_client

    async def get_current(self, *, request_options: typing.Optional[RequestOptions] = None) -> OrganizationEnvelope:
        """
        Returns the organization the caller is authenticated against.

        This endpoint is the safest way to discover the effective organization for a
        user-scoped or organization-scoped credential. It does not let callers inspect
        arbitrary organizations; it only returns the organization implied by the
        credential that authenticated the request.

        If you need to enumerate or look up organizations across a partner account, use
        [`GET /api/organizations`](../../api-reference/organization/list) or
        [`GET /api/organizations/{id}`](../../api-reference/organization/get) instead.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.get_current()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_current(request_options=request_options)
        return _response.data

    async def get_record_logging(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RecordLoggingSettingsEnvelope:
        """
        Returns the organization's record logging settings, including the connection record logs are delivered to.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecordLoggingSettingsEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.get_record_logging()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_record_logging(request_options=request_options)
        return _response.data

    async def update_record_logging(
        self,
        *,
        enabled: bool,
        delivery_connection_id: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RecordLoggingSettingsEnvelope:
        """
        Replaces the organization's record logging settings. `deliveryConnectionId` is replaced, not merged: omitting it, or sending null, removes any destination previously configured.

        Parameters
        ----------
        enabled : bool
            Whether record logging is enabled for the organization.

        delivery_connection_id : typing.Optional[str]
            Blobstorage connection that receives record logs after each model sync execution. Omit or send null to deliver nowhere; this field is replaced, not merged.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecordLoggingSettingsEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.update_record_logging(
                enabled=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_record_logging(
            enabled=enabled,
            delivery_connection_id=delivery_connection_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> OrganizationsEnvelope:
        """
        Lists every organization accessible to the calling partner, with the partner's owner organization first.

        In `2025-09-18`, this endpoint is partner-scoped rather than a general
        "current caller visibility" listing. The partner owner organization is returned
        first, followed by child organizations.

        This ordering matters for partner workflows such as shared connections, where
        the parent connection must live in the partner owner organization.

        If you need only the organization implied by the current credential, use
        [`GET /api/organization`](../../api-reference/organization/get-current) instead.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationsEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        name: str,
        client_id: typing.Optional[str] = OMIT,
        client_secret: typing.Optional[str] = OMIT,
        issuer: typing.Optional[str] = OMIT,
        sso_domain: typing.Optional[str] = OMIT,
        sso_org_id: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrganizationEnvelope:
        """
        Creates a new organization under the calling partner account, optionally configuring SSO or OIDC at creation time.

        > 🚧 Requires partner key
        >
        > This endpoint is only accessible using [partner keys](../../guides/obtaining-api-keys#partner-keys).

        SSO and OIDC settings supplied at creation time can be updated later via
        `PUT /api/organizations/{id}`.

        Parameters
        ----------
        name : str
            Human-readable name of the organization. Must be unique across the partner account.

        client_id : typing.Optional[str]
            OIDC client ID issued by the identity provider.

        client_secret : typing.Optional[str]
            OIDC client secret issued by the identity provider. Write-only; never returned in responses.

        issuer : typing.Optional[str]
            OIDC issuer URL for organizations using OpenID Connect single sign-on.

        sso_domain : typing.Optional[str]
            Email domain used to match users to this organization during SSO sign-in.

        sso_org_id : typing.Optional[str]
            WorkOS organization identifier linking this organization to its SAML/SSO configuration.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.create(
                name="My Organization",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            name=name,
            client_id=client_id,
            client_secret=client_secret,
            issuer=issuer,
            sso_domain=sso_domain,
            sso_org_id=sso_org_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> OrganizationEnvelope:
        """
        Returns a single organization by ID.

        > 📘 Credential scope varies by endpoint and API version
        >
        > Organization endpoints do not all share the same credential requirements.
        > Check each endpoint's description for the caller scope that applies in that
        > API version.

        Parameters
        ----------
        id : str
            Unique identifier of the organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.get(
                id="248df4b7-aa70-47b8-a036-33ac447e668d",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        name: str,
        client_id: typing.Optional[str] = OMIT,
        client_secret: typing.Optional[str] = OMIT,
        issuer: typing.Optional[str] = OMIT,
        sso_domain: typing.Optional[str] = OMIT,
        sso_org_id: typing.Optional[str] = OMIT,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrganizationEnvelope:
        """
        Updates an organization's name and SSO or OIDC configuration.

        > 🚧 Requires partner key
        >
        > This endpoint is only accessible using [partner keys](../../../guides/obtaining-api-keys#partner-keys).

        > 📘 SSO and OIDC configuration is replaced in full on each update. Include all
        > desired settings in the request body, not just the fields you want to change.

        Parameters
        ----------
        id : str
            Unique identifier of the organization to update.

        name : str
            Human-readable name of the organization. Must be unique across the partner account.

        client_id : typing.Optional[str]
            OIDC client ID issued by the identity provider.

        client_secret : typing.Optional[str]
            OIDC client secret issued by the identity provider. Write-only; never returned in responses.

        issuer : typing.Optional[str]
            OIDC issuer URL for organizations using OpenID Connect single sign-on.

        sso_domain : typing.Optional[str]
            Email domain used to match users to this organization during SSO sign-in.

        sso_org_id : typing.Optional[str]
            WorkOS organization identifier linking this organization to its SAML/SSO configuration.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationEnvelope
            OK

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.update(
                id="248df4b7-aa70-47b8-a036-33ac447e668d",
                name="My Organization",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            name=name,
            client_id=client_id,
            client_secret=client_secret,
            issuer=issuer,
            sso_domain=sso_domain,
            sso_org_id=sso_org_id,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def delete(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Deletes an organization.

        Partner callers cannot delete their own owner organization.

        Parameters
        ----------
        id : str
            Unique identifier of the organization.

        idempotency_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from polytomic import AsyncPolytomic

        client = AsyncPolytomic(
            "2025-09-18",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.delete(
                id="248df4b7-aa70-47b8-a036-33ac447e668d",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data
