# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class V2UpdateSyncRequestMode(str, enum.Enum):
    UPDATE = "update"
    UPDATE_OR_CREATE = "updateOrCreate"
    CREATE = "create"
    REPLACE = "replace"
    APPEND = "append"
    SNAPSHOT = "snapshot"

    def visit(
        self,
        update: typing.Callable[[], T_Result],
        update_or_create: typing.Callable[[], T_Result],
        create: typing.Callable[[], T_Result],
        replace: typing.Callable[[], T_Result],
        append: typing.Callable[[], T_Result],
        snapshot: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is V2UpdateSyncRequestMode.UPDATE:
            return update()
        if self is V2UpdateSyncRequestMode.UPDATE_OR_CREATE:
            return update_or_create()
        if self is V2UpdateSyncRequestMode.CREATE:
            return create()
        if self is V2UpdateSyncRequestMode.REPLACE:
            return replace()
        if self is V2UpdateSyncRequestMode.APPEND:
            return append()
        if self is V2UpdateSyncRequestMode.SNAPSHOT:
            return snapshot()
